- name: Make sure the known hosts file exists
  file: "path={{ ssh_known_hosts_file }} state=touch"
  tags: hadoop

- name: test hostvars
  shell: "if ( ssh-keyscan {{ hostvars[item].hostname }}  | xargs  -i grep {} /etc/ssh/ssh_known_hosts); then   echo 0; else    ssh-keyscan {{ hostvars[item].hostname }} >> {{ ssh_known_hosts_file }}; fi "
  with_items: "{{ groups['hadoop'] }}"
  register: ssh_known_host_results_hostname
  tags: hadoop


