- name: Make sure the known hosts file exists
  file: "path={{ ssh_known_hosts_file }} state=touch"
  tags: hadoop

- name: Check host name availability
  shell: "ssh-keygen -f {{ ssh_known_hosts_file }} -F {{ item }}"
  with_items: groups['hadoop']
  register: ssh_known_host_results
  tags: hadoop

- name: Scan the public key
  shell: "{{ ssh_known_hosts_command}} {{ item.item }} >> {{ ssh_known_hosts_file }}"
  with_items: ssh_known_host_results.results
  when: item.stdout == ""
  tags: hadoop
  