# - name: start zookeeper
#   service: name=zookeeper state=started enabled=yes

# - name: restart zookeeper
#   service: name=zookeeper state=restarted enabled=yes

- name: start zookeeper
  command: su - zookeeper /bin/bash -c  "{{ zk_dir }}/bin/zkServer.sh start"
  tags: zk

- name: restart zookeeper
  command: su - zookeeper /bin/bash -c  "{{ zk_dir }}/bin/zkServer.sh restart"
  tags: zk