# - name: install wget
#   yum: name=wget,libselinux-python state=present
#   tags: java8

- name: create /usr/java directory
  file: path=/usr/java state=directory owner=root group=root mode=0755
  tags: java8

- name: Copy and UnArchive the Package in Destination Server.
  unarchive: creates=/usr/java/jdk{{ jdk8_version }} src=file_archives/jdk-{{ jdk8_pkg_version }}-linux-x64.tar.gz dest=/usr/java
  tags: java8

# - name: extract jdk8
#   command: >
#     tar -xf file_archives/jdk-{{ jdk8_pkg_version }}-linux-x64.tar.gz
#     chdir=/usr/java
#     creates=/usr/java/jdk{{ jdk8_version }}
#   tags: java8

- name: symlink to /usr/local
  file: >
    state=link
    src=/usr/java/jdk{{ jdk8_version }}
    dest=/usr/local/{{  symlink_to  }}
    owner=root group=root
  tags: java8

- name: /etc/profile.d/java8.sh
  template: >
    src=profile.java8.sh.j2
    dest=/etc/profile.d/{{  symlink_to  }}.sh
    owner=root group=root mode=0644
  tags: java8
