# - name: Remove datanode data
#   file: path="{{ hadoop_hdfs.dfs_dir_datanode }}"  state=absent
#   tags: hadoop

- name: Stop DFS 
  command:  su - {{ hadoop_user }} /bin/bash -c "stop-dfs.sh"
  tags: hadoop

- name: Start DFS Again
  command: su - {{ hadoop_user }} /bin/bash -c "start-dfs.sh"
  tags: hadoop
