# - name: Remove datanode data
#   file: path="{{ hadoop_hdfs.dfs_dir_datanode }}"  state=absent
#   tags: hadoop

- name: Stop DFS To Remove datanode data
  command:  stop-dfs.sh
  tags: hadoop

- name: Start DFS Again
  command: start-dfs.sh
  tags: hadoop
